data_folder: "../dataset/fluent_speech_commands_dataset"
dataset: "fsc"
batch_size: 64
epochs: 20
n_fft:  1200
n_mels: 256
train_split: "train"
valid_split: "valid"
test_split: "test"
text_model: "transformer"
audio_model: "transformer"
embed_dim: 128
hidden_dim: 64
output_dim: 31
trainable: true
from_pretrain: false
weight_decay: 1e-1
audio_lr: 5e-4
classifier_lr: 2e-3
cp_path: "checkpoints/librispeech360-clap-pretrain-larger-model-and-batch.pt"
finetune_cp_path: "checkpoints/librispeech360-clap-pretrain-fsc-finetune-02.pt"
device: "cuda:1"
beta_1: 0.9
beta_2: 0.999
eps: 1e-9