data_folder: "../dataset/fluent_speech_commands_dataset"
dataset: "fsc"
batch_size: 8
epochs: 20
n_fft:  1200
n_mels: 256
train_split: "train"
valid_split: "valid"
test_split: "test"
embed_dim: 256
hidden_dim: 512
output_dim: 31
trainable: true
from_pretrain: true
weight_decay: 2e-1
audio_lr: 2e-4
classifier_lr: 2e-3
cp_path: "checkpoints/librispeech360-clap-pretrain-both-pretrain.pt"
finetune_cp_path: "checkpoints/librispeech360-clap-finetune-both-pretrain.pt"
device: "cuda:0"
beta_1: 0.9
beta_2: 0.999
eps: 1e-9