data_folder: "../dataset/fluent_speech_commands_dataset"
dataset: "fsc"
batch_size: 8
epochs: 10
num_mel_bins: 40
num_ceps: 13
high_freq: -400
train_split: "train"
valid_split: "valid"
test_split: "test"
n_fft:  6400
n_mels: 768
audio_model: "transformer"
embed_dim: 256
weight_decay: 2e-1
lr: 5e-4
cp_path: "checkpoints/librispeech-clap-pretrain.pt"
device: "cuda:1"
beta_1: 0.9
beta_2: 0.98
eps: 1e-6