data_folder: "../dataset"
download: true
tokenizer: "bert-base-uncased"
dataset: "librispeech"
batch_size: 8
epochs: 15
warm_up_epochs: 3
stepsize: 1
n_fft:  800
n_mels: 128
train_split: "train-clean-360"
valid_split: "dev-clean"
test_split: "test-clean"
text_model: "transformer"
audio_model: "transformer"
embed_dim: 128
weight_decay: 1e-2
lr: 1e-5
patience: 2
factor: 0.7
cp_path: "checkpoints/librispeech360-clap-pretrain.pt"
device: "cuda:1"
beta_1: 0.9
beta_2: 0.999
eps: 1e-9