data_folder: "../dataset"
download: false
tokenizer: "bert-base-uncased"
dataset: "librispeech"
batch_size: 4
epochs: 30
num_mel_bins: 80
num_ceps: 64
high_freq: -400
train_split: "train-clean-100"
valid_split: "dev-clean"
test_split: "test-clean"
text_model: "transformer"
audio_model: "transformer"
embed_dim: 512
weight_decay: 1e-4
lr: 1e-3
patience: 1
factor: 0.8
cp_path: "checkpoints/librispeech-clap-pretrain.pt"