data_folder: "../dataset"
download: true
tokenizer: "distilbert-base-uncased"
dataset: "librispeech"
batch_size: 3
epochs: 3
warm_up_epochs: 3
stepsize: 1
n_fft:  3500
n_mels: 768
train_split: "train-clean-360"
valid_split: "dev-clean"
test_split: "test-clean"
embed_dim: 512
weight_decay: 1e-2
lr: 1e-5
patience: 2
factor: 0.7
cp_path: "checkpoints/librispeech360-clap-pretrain-only-projection.pt"
device: "cuda:0"
beta_1: 0.9
beta_2: 0.999
eps: 1e-9
save_step: 0
